// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5O085nRoZfjSDM3HHqltNp0N_UQUj0p4',
    appId: '1:488843236274:android:b88626861962c5208bcaab',
    messagingSenderId: '488843236274',
    projectId: 'subscriptions-app-9590f',
    databaseURL: 'https://subscriptions-app-9590f-default-rtdb.firebaseio.com',
    storageBucket: 'subscriptions-app-9590f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgo91MgYX1S-k7jgw_rpSdG6FUrSlFpa4',
    appId: '1:488843236274:ios:9db83dfb732d28e58bcaab',
    messagingSenderId: '488843236274',
    projectId: 'subscriptions-app-9590f',
    databaseURL: 'https://subscriptions-app-9590f-default-rtdb.firebaseio.com',
    storageBucket: 'subscriptions-app-9590f.firebasestorage.app',
    iosBundleId: 'com.ccc218.subscriptionsapp',
  );

}